BOF/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from BOF import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('post.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from account.views import register_view, login_view, logout_view, search_view, requests_list_view, send_request_view, \
        accept_request_view, decline_request_view, profile_view, settings_view
from django.urls import path

app_name = "account"
urlpatterns = [
        path('login/', login_view, name='login-view'),
        path('logout/', logout_view, name='logout-view'),
        path('register/', register_view, name='register-view'),
        path('search/', search_view, name='search-view'),
        path('requests/', requests_list_view, name='requests-list-view'),
        path('send-request/<int:id>/', send_request_view, name='send-request-view'),
        path('accept-request/<int:id>/', accept_request_view, name='accept-request-view'),
        path('decline-request/<int:id>/', decline_request_view, name='decline-request-view'),
        path('profile/<int:id>', profile_view, name='profile-view'),
        path('settings/', settings_view, name='settings-view'),
    ]

templates/head.html
<!DOCTYPE HTML>
<html lang = "pl">

<head>

    <title>Book of Face</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
</head>
<body>
    <div class="navbar">
        <h1> <a href="/">BoF</a></h1> 
        <div class="search">
            <form method="GET", action="{% url 'account:search-view'%}">
                <input type="search" placeholder="Szukaj na BoF", name="query", value="{{request.GET.query}}">
                <button-8 class="icon", type="submit">Szukaj w BoF</button-8>
                
            </form>
            <d><a href="/requests">Zaproszenia</a> <a href="{{user.account.get_absolute_url}}">Profil</i></a> <a href="/settings">Ustawienia</a > <a href="/logout">Wyloguj</a > <d/>

        </div>    
    </div>
    <div class="content">
        {%block content%}
        replace me
        {%endblock%}
    </div>

</body>
</html>